---
title: LSIDEM02
subtitle: Randomization Listing
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(rtables.officer)

envsetup_config_name <- "default"

# Path to the combined config file
envsetup_file_path <- file.path("../..", "envsetup.yml")

Sys.setenv(ENVSETUP_ENVIRON = '')
library(envsetup)
loaded_config <- config::get(config = envsetup_config_name, file = envsetup_file_path)
envsetup::rprofile(loaded_config)


dpscomp <- compound
dpspdr <- paste(protocol,dbrelease,rpteff,sep="__")

aptcomp <- compound
aptpdr <- paste(protocol,dbrelease,rpteff,sep="__")

###### Study specific updates (formerly in envre)

dpscomp <- "standards"
dpspdr <- "jjcs__NULL__jjcs - core"

apt <- FALSE

```

## Output

:::: panel-tabset
## {{< fa regular file-lines sm fw >}} Preview

```{r variant1, results='hide', warning = FALSE, message = FALSE}

# Program Name:              lsidem02.R

# Prep environment

library(envsetup)
library(tern)
library(dplyr)
library(rtables)
library(junco)

# Define script level parameters

tblid <- "LSIDEM02"
fileid <- tblid
popfl <- "RANDFL"
key_cols <- c("COL1")
disp_cols <- paste0("COL", 1:9)
concat_sep <- " / "
tab_titles <- get_titles_from_file(input_path = '../../_data/', tblid)
string_map <- default_str_map

# Process data

adsl <- pharmaverseadamjnj::adsl %>%
  filter(!!rlang::sym(popfl) == "Y")

lsting <- adsl %>%
  mutate(
    COL1 = explicit_na(USUBJID, ""),
    COL2 = explicit_na(REGION1, ""),
    COL3 = explicit_na(COUNTRY_DECODE, ""),
    COL4 = case_when(
      !is.na(RANDDT) & any(names(adsl) == "RANDDTM") & !is.na(RANDDTM) ~
        paste0(
          toupper(format(RANDDT, "%d%b%Y")),
          concat_sep,
          substr(RANDDTM, 12, 16)
        ),
      !is.na(RANDDT) & any(names(adsl) == "RANDDTM") & is.na(RANDDTM) ~
        paste0(toupper(format(RANDDT, "%d%b%Y")), concat_sep, "--:--"),
      !is.na(RANDDT) & !any(names(adsl) == "RANDDTM") ~
        paste0(toupper(format(RANDDT, "%d%b%Y"))),
    ),
    COL5 = explicit_na(RANUM, ""),
    # Optional Column: COL6/STRAT1R
    COL6 = explicit_na(STRAT1R, ""),
    # Optional Column: COL7/STRAT2R
    COL7 = explicit_na(STRAT2R, ""),
    COL8 = explicit_na(TRT01P, ""),
    COL9 = explicit_na(TRT01A, "")
  ) %>%
  arrange(COL1)

lsting <- var_relabel(lsting,
  COL1 = "Subject ID",
  COL2 = "Region",
  COL3 = paste("Country", "Territory", sep = concat_sep),
  COL4 = paste("Randomization Date", "Time", sep = concat_sep),
  COL5 = "Randomization Number",
  # Optional Column: COL6/STRAT1R
  COL6 = "Stratification Factor 1",
  # Optional Column: COL7/STRAT2R
  COL7 = "Stratification Factor 2",
  COL8 = "Randomization Treatment Assignment",
  COL9 = "Actual Treatment"
)

# Build listing

result <- rlistings::as_listing(
  df = lsting,
  key_cols = c("COL1"),
  disp_cols = disp_cols
)

# Add titles and footnotes

result <- set_titles(result, tab_titles)

# Output listing

tt_to_tlgrtf(string_map = string_map, tt = head(result, 30), file = fileid, orientation = "landscape")
```
```{r result1, echo=FALSE, message=FALSE, warning=FALSE, test = list(result_v1 = "result")}
tt_to_flextable(head(result,100), theme = theme_docx_default(font_size = 6))
```

[Download RTF file](`r paste0(tolower(tblid), '.rtf')`)
::::

