---
title: LSFLAB01
subtitle: Listing of Subjects With Criteria Laboratory Values
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(rtables.officer)

envsetup_config_name <- "default"

# Path to the combined config file
envsetup_file_path <- file.path("../..", "envsetup.yml")

Sys.setenv(ENVSETUP_ENVIRON = '')
library(envsetup)
loaded_config <- config::get(config = envsetup_config_name, file = envsetup_file_path)
envsetup::rprofile(loaded_config)


dpscomp <- compound
dpspdr <- paste(protocol,dbrelease,rpteff,sep="__")

aptcomp <- compound
aptpdr <- paste(protocol,dbrelease,rpteff,sep="__")

###### Study specific updates (formerly in envre)

dpscomp <- "standards"
dpspdr <- "jjcs__NULL__jjcs - core"

apt <- FALSE

```

## Output

:::: panel-tabset
## {{< fa regular file-lines sm fw >}} Preview

```{r variant1, results='hide', warning = FALSE, message = FALSE}

# Program Name:              lsflab01.R

# Prep environment

library(envsetup)
library(tern)
library(dplyr)
library(rtables)
library(junco)

# Define script level parameters

tblid <- "LSFLAB01"
fileid <- tblid
popfl <- "SAFFL"
trtvar <- "TRT01A"
key_cols <- c("COL0", "COL1", "COL2", "COL3")
disp_cols <- paste0("COL", 0:10)
concat_sep <- " / "
tab_titles <- get_titles_from_file(input_path = '../../_data/', tblid)
string_map <- default_str_map

# Process data

adlb <- pharmaverseadamjnj::adlb %>%
  filter(!!rlang::sym(popfl) == "Y" & is.na(DTYPE))


adlb <- adlb[1:1000,] #make it manageable

adlb_crit <- adlb %>%
  # Update filter criteria as needed for your study
  # MCRIT1ML/MCRI2ML or ATOXGRN will be used
  filter(((!is.na(MCRIT1ML) & as.numeric(substr(MCRIT1ML, 7, 8)) >= 2) |
    (!is.na(MCRIT2ML) & as.numeric(substr(MCRIT2ML, 7, 8)) >= 2))) %>%
  # filter(ATOXGRN >= 3) %>%
  select(STUDYID, USUBJID, PARAMCD) %>%
  distinct()

adlb_dig <- tidytlg:::make_precision_data(
  df = adlb,
  decimal = 4,
  precisionby = "PARAMCD",
  precisionon = "AVAL"
) %>%
  rename(c(VALDIGMAX = "decimal"))

adlb_list <- adlb_crit %>%
  inner_join(adlb, by = c(
    "STUDYID" = "STUDYID",
    "USUBJID" = "USUBJID",
    "PARAMCD" = "PARAMCD"
  )) %>%
  inner_join(adlb_dig, by = c("PARAMCD" = "PARAMCD"))

lsting <- adlb_list %>%
  mutate(
    AGE = explicit_na(as.character(AGE), ""),
    SEX = explicit_na(SEX, ""),
    RACE_DECODE = explicit_na(RACE_DECODE, ""),
    ADT = ifelse(nchar(as.character(ADT)) == 10,
      toupper(format(ADT, "%d%b%Y")),
      "---------"
    ),
    ATM = ifelse(!is.na(ADTM), substr(as.character(ADTM), 12, 16), "--:--"),
    ADYN = ifelse(!is.na(ADY), ADY, NA),
    ADY = ifelse(!is.na(ADY), ADY, "--"),
    VAL = case_when(
      is.na(VALDIGMAX) & !is.na(AVAL) ~
        tidytlg::roundSAS(AVAL, digits = 0, as_char = TRUE, na_char = NULL),
      VALDIGMAX == 0 & !is.na(AVAL) ~
        tidytlg::roundSAS(AVAL, digits = 0, as_char = TRUE, na_char = NULL),
      VALDIGMAX == 1 & !is.na(AVAL) ~
        tidytlg::roundSAS(AVAL, digits = 1, as_char = TRUE, na_char = NULL),
      VALDIGMAX == 2 & !is.na(AVAL) ~
        tidytlg::roundSAS(AVAL, digits = 2, as_char = TRUE, na_char = NULL),
      VALDIGMAX == 3 & !is.na(AVAL) ~
        tidytlg::roundSAS(AVAL, digits = 3, as_char = TRUE, na_char = NULL),
      VALDIGMAX >= 4 & !is.na(AVAL) ~
        tidytlg::roundSAS(AVAL, digits = 4, as_char = TRUE, na_char = NULL),
      !is.na(AVALC) ~ AVALC
    ),
    ANRIND = substr(ANRIND, 1, 1),
    MCRIT1ML = ifelse(MCRIT1ML != "Level 0",
      paste0(
        "L", substr(MCRIT1ML, 7, 8),
        substr(
          MCRIT1ML, 9,
          nchar(as.character(MCRIT1ML))
        )
      ),
      NA
    ),
    MCRIT2ML = ifelse(MCRIT2ML != "Level 0",
      paste0(
        "L", substr(MCRIT2ML, 7, 8),
        substr(
          MCRIT2ML, 9,
          nchar(as.character(MCRIT2ML))
        )
      ),
      NA
    ),
    CRIT = case_when(
      is.na(MCRIT1ML) & is.na(MCRIT2ML) ~ "",
      !is.na(MCRIT1ML) ~ MCRIT1ML,
      !is.na(MCRIT2ML) ~ MCRIT2ML,
    ),
    # CRIT = ifelse(!is.na(ATOXGR), as.character(ATOXGR), ""),
    REFR = case_when(
      !is.na(ANRLO) & !is.na(ANRHI) ~ paste(ANRLO, ANRHI, sep = "-"),
      !is.na(ANRLO) & is.na(ANRHI) ~ paste(ANRLO, "", sep = "-"),
      is.na(ANRLO) & !is.na(ANRHI) ~ paste("", ANRHI, sep = "-")
    ),
    COL0 = explicit_na(.data[[trtvar]], ""),
    COL1 = explicit_na(USUBJID, ""),
    COL2 = paste(AGE, SEX, RACE_DECODE, sep = concat_sep),
    COL3 = explicit_na(PARAM, ""),
    # Optional Variable: ATM
    COL4 = paste0(ADT, concat_sep, ATM, " (", ADY, ")", sep = ""),
    COL5 = explicit_na(AVISIT, ""),
    # Optional Column: COL6/ATPT
    COL6 = explicit_na(ATPT, ""),
    COL7 = explicit_na(VAL, ""),
    # Optional Variable: COL8/MCRIT1ML/MCRIT2ML/ATOXGR
    COL8 = explicit_na(CRIT, ""),
    COL9 = case_when(
      is.na(CHG) ~ "",
      is.na(VALDIGMAX) & !is.na(AVAL) & !is.na(CHG) ~
        tidytlg::roundSAS(CHG, digits = 0, as_char = TRUE, na_char = NULL),
      VALDIGMAX == 0 & !is.na(CHG) ~
        tidytlg::roundSAS(CHG, digits = 0, as_char = TRUE, na_char = NULL),
      VALDIGMAX == 1 & !is.na(CHG) ~
        tidytlg::roundSAS(CHG, digits = 1, as_char = TRUE, na_char = NULL),
      VALDIGMAX == 2 & !is.na(CHG) ~
        tidytlg::roundSAS(CHG, digits = 2, as_char = TRUE, na_char = NULL),
      VALDIGMAX == 3 & !is.na(CHG) ~
        tidytlg::roundSAS(CHG, digits = 3, as_char = TRUE, na_char = NULL),
      VALDIGMAX >= 4 & !is.na(CHG) ~
        tidytlg::roundSAS(CHG, digits = 4, as_char = TRUE, na_char = NULL)
    ),
    # Optional Column: COL10/ANRLO/ANRHI
    COL10 = explicit_na(REFR, ""),
  ) %>%
  arrange(COL0, COL1, COL2, COL3, COL4, !is.na(ADYN), ADYN, ADTM)

lsting <- var_relabel(lsting,
  COL0 = "Treatment Group",
  COL1 = "Subject ID",
  COL2 = paste("Age (years)", "Sex", "Race", sep = concat_sep),
  COL3 = "Laboratory Test (unit)",
  # Optional Variable: ATM
  COL4 = paste("Assessment Date",
    "Time (Study Day~[super a])",
    sep = concat_sep
  ),
  COL5 = "Visit",
  # Optional Column: COL6/ATPT
  COL6 = "Time Point",
  COL7 = "Result",
  # Optional Variable: COL8/MCRIT1ML/MCRIT2ML/ATOXGR
  COL8 = "FDA Threshold Level",
  # COL9 = "Toxicity Grade",
  COL9 = "Change From Baseline",
  # Optional Column: COL10/ANRLO/ANRHI
  COL10 = "Reference Range"
)

# Build listing

result <- rlistings::as_listing(
  df = lsting,
  key_cols = key_cols,
  disp_cols = disp_cols
)

# Add titles and footnotes

result <- set_titles(result, tab_titles)

# Output listing

tt_to_tlgrtf(string_map = string_map, tt = head(result, 30), file = fileid, orientation = "landscape")
```
```{r result1, echo=FALSE, message=FALSE, warning=FALSE, test = list(result_v1 = "result")}
tt_to_flextable(head(result,30), theme = theme_docx_default(font_size = 6))
```

[Download RTF file](`r paste0(tolower(tblid), '.rtf')`)
::::

