---
title: TSIEX07
subtitle: Dose Levels Over Time
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}


envsetup_config_name <- "default"

# Path to the combined config file
envsetup_file_path <- file.path("../..", "envsetup.yml")

Sys.setenv(ENVSETUP_ENVIRON = '')
library(envsetup)
loaded_config <- config::get(config = envsetup_config_name, file = envsetup_file_path)
envsetup::rprofile(loaded_config)


dpscomp <- compound
dpspdr <- paste(protocol,dbrelease,rpteff,sep="__")

aptcomp <- compound
aptpdr <- paste(protocol,dbrelease,rpteff,sep="__")

###### Study specific updates (formerly in envre)

dpscomp <- "standards"
dpspdr <- "jjcs__NULL__jjcs - core"

apt <- FALSE

```

## Output

:::: panel-tabset
## {{< fa regular file-lines sm fw >}} Preview

```{r variant1, results='hide', warning = FALSE, message = FALSE}

# Program Name: tsiex07.R

# Prep Environment

library(envsetup)
library(tern)
library(dplyr)
library(rtables)
library(junco)

# Define script level parameters:

# - Define output ID and file location

tblid <- "TSIEX07"
fileid <- tblid
tab_titles <- get_titles_from_file(input_path = '../../_data/', tblid)
string_map <- default_str_map


trtvar <- "TRT01A"
popfl <- "SAFFL"

dose_order <- c("60", "120", "180", "240", "300", "480", "720", "960", "Total")

# Process Data:

# Read in required data
adsl <- pharmaverseadamjnj::adsl %>%
  filter(!!rlang::sym(popfl) == "Y" & !!rlang::sym(trtvar) != "Placebo") %>%
  select(USUBJID, all_of(trtvar), all_of(popfl))

adex <- pharmaverseadamjnj::adex %>%
  filter(!grepl("UNSCHEDULED", AVISIT, ignore.case = TRUE)) %>%
  filter(!is.na(ADOSE)) %>%
  mutate(ADOSEC = as.factor(ADOSE)) %>%
  select(USUBJID, ADOSEC, AVISIT, AVISITN)

# Convert AVISIT to sentence case and apply levels to maintain ordering
avisit_levs <- stringr::str_to_sentence(levels(adex$AVISIT))
adex$AVISIT <- stringr::str_to_sentence(adex$AVISIT)
adex$AVISIT <- factor(adex$AVISIT, levels = avisit_levs)

# Create Total column manually as we cannot use the table layout option since patients can
# appear in multiple dose level columns

extot_ <- adex %>%
  group_by(USUBJID, AVISIT) %>%
  slice(1) %>%
  mutate(ADOSEC = "Total") %>%
  ungroup()

extot <- bind_rows(adex, extot_)

# join data together
ex <- extot %>% inner_join(., adsl, by = c("USUBJID"))

ex$colspan_trt <- factor(ifelse(ex$ADOSEC == "Total", " ", "Active Study Agent"),
  levels = c("Active Study Agent", " ")
)

ex$ADOSEC <- factor(ex$ADOSEC, levels = dose_order)

# Create dataset to be used for column counts
adex_unique <- ex %>%
  group_by(USUBJID, ADOSEC) %>%
  slice(1) %>%
  ungroup()

# Define layout and build table:

lyt <- rtables::basic_table(
  top_level_section_div = " ",
  show_colcounts = TRUE,
  colcount_format = "N=xx"
) %>%
  split_cols_by("colspan_trt", split_fun = trim_levels_in_group("ADOSEC")) %>%
  split_cols_by("ADOSEC") %>%
  tern::count_occurrences("AVISIT",
    .stats = "count_fraction_fixed_dp",
    .formats = c("count_fraction_fixed_dp" = jjcsformat_count_fraction),
    var_labels = " ", show_labels = "hidden"
  ) %>%
  append_topleft("Time Point, n (%)")

result <- build_table(lyt, ex, alt_counts_df = adex_unique)

# Add titles and footnotes:

result <- set_titles(result, tab_titles)

# Convert to tbl file and output table

tt_to_tlgrtf(string_map = string_map, tt = head(result, 20), file = fileid, orientation = "landscape")
```
```{r result1, echo=FALSE, message=FALSE, warning=FALSE, test = list(result_v1 = "result")}
tt_to_flextable_j(head(result, 20), tblid)
```

[Download RTF file](`r paste0(tolower(tblid), '.rtf')`)
::::

