---
title: TSFAE24D
subtitle: Subjects With Treatment-emergent Adverse Events Toxicity Grade ≥3 With Frequency ≥x% in Any Treatment Group by System Organ Class and Preferred Term
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}


envsetup_config_name <- "default"

# Path to the combined config file
envsetup_file_path <- file.path("../..", "envsetup.yml")

Sys.setenv(ENVSETUP_ENVIRON = '')
library(envsetup)
loaded_config <- config::get(config = envsetup_config_name, file = envsetup_file_path)
envsetup::rprofile(loaded_config)


dpscomp <- compound
dpspdr <- paste(protocol,dbrelease,rpteff,sep="__")

aptcomp <- compound
aptpdr <- paste(protocol,dbrelease,rpteff,sep="__")

###### Study specific updates (formerly in envre)

dpscomp <- "standards"
dpspdr <- "jjcs__NULL__jjcs - core"

apt <- FALSE

```

## Output

:::: panel-tabset
## {{< fa regular file-lines sm fw >}} Preview

```{r variant1, results='hide', warning = FALSE, message = FALSE}

# Program Name:              tsfae24d.R

# Prep environment:

library(envsetup)
library(tern)
library(dplyr)
library(rtables)
library(junco)

# Define script level parameters:

tblid <- "TSFAE24d"
fileid <- tblid
popfl <- "SAFFL"
trtvar <- "TRT01A"
tab_titles <- get_titles_from_file(input_path = '../../_data/', tblid)
string_map <- default_str_map

# Process data:

adsl <- pharmaverseadamjnj::adsl %>%
  filter(!!rlang::sym(popfl) == "Y") %>%
  create_colspan_var(
    non_active_grp          = "Placebo",
    non_active_grp_span_lbl = " ",
    active_grp_span_lbl     = "Active Study Agent",
    colspan_var             = "colspan_trt",
    trt_var                 = trtvar
  ) %>%
  mutate(COLSPAN_TOX = "AEs") %>%
  select(USUBJID, !!rlang::sym(popfl), !!rlang::sym(trtvar), colspan_trt, COLSPAN_TOX)

adae <- pharmaverseadamjnj::adae %>%
  filter(TRTEMFL == "Y") %>%
  mutate(TOXGE3 = ifelse(AETOXGRN == 3 | AETOXGRN > 3, ">= 3", "< 3")) %>%
  select(USUBJID, TRTEMFL, AEBODSYS, AEDECOD, AETOXGR, TOXGE3)

adae <- inner_join(adae, adsl, by = c("USUBJID"))

# Define layout and build table:

colspan_trt_map <- create_colspan_map(adsl,
  non_active_grp = "Placebo",
  non_active_grp_span_lbl = " ",
  active_grp_span_lbl = "Active Study Agent",
  colspan_var = "colspan_trt",
  trt_var = trtvar
)

add_active_combo <- make_split_fun(
  post = list(
    add_combo_facet(
      name = "Combined",
      label = "Combined",
      levels = c("Apalutamide", "Apalutamide Subgroup")
    ),
    cond_rm_facets(
      facets = "Combined",
      ancestor_pos = NA,
      value = " ",
      split = "colspan_trt"
    )
  )
)

# Create "TOX > 3" facet.
add_tox_levels <- make_split_fun(
  post = list(add_combo_facet(
    name = "TOXGR",
    label = ">= Grade 3 AEs",
    levels = c("AEs")
  ))
)

extra_args1 <- list(.stats = c("count_unique_fraction"),
                    subcol_split = "TOXGR",
                    subcol_var = "TOXGE3",
                    subcol_val = ">= 3")

lyt <- basic_table(top_level_section_div = " ") %>%
  split_cols_by("colspan_trt", split_fun = trim_levels_to_map(map = colspan_trt_map)) %>%
  split_cols_by(trtvar, split_fun = add_active_combo, show_colcounts = TRUE, colcount_format = "N=xx") %>%
  split_cols_by("COLSPAN_TOX", split_fun = add_tox_levels) %>%
  analyze("TRTEMFL",
    nested = FALSE, 
    afun = a_freq_subcol_j,
    extra_args = append(extra_args1, list(
      label = "Subjects with >= 1 AE",
      val = "Y"))
  ) %>%
  split_rows_by("AEBODSYS",
    split_label = "System Organ Class",
    label_pos   = "topleft",
    split_fun   = trim_levels_in_group("AEDECOD"),
    section_div = " ",
    nested      = FALSE
  ) %>%
  summarize_row_groups("AEBODSYS",
    cfun = a_freq_subcol_j,
    extra_args = extra_args1
  ) %>%
  analyze("AEDECOD", 
          afun = a_freq_subcol_j, 
          extra_args = extra_args1
  ) %>%
  append_topleft(" Preferred Term, n (%)")

result <- build_table(lyt, adae, alt_counts_df = adsl)

# Post-Processing:

result <- result %>%
  sort_at_path(path = c("AEBODSYS"), scorefun = cont_n_onecol("Active Study Agent.Combined.TOXGR")) %>%
  sort_at_path(path = c("AEBODSYS", "*", "AEDECOD"), scorefun = score_occurrences_cols("Active Study Agent.Combined.TOXGR"))

row_condition <- has_fraction_in_any_col(
  atleast = .02,
  col_names = c(
    "Active Study Agent.Apalutamide.TOXGR",
    "Active Study Agent.Apalutamide Subgroup.TOXGR",
    "Active Study Agent.Combined.TOXGR",
    " .Placebo.TOXGR"
  )
)

result <- safe_prune_table(result, keep_rows(row_condition))

# Add titles and footnotes:

result <- set_titles(result, tab_titles)

# Convert to tbl file and output table:

tt_to_tlgrtf(string_map = string_map, tt = head(result, 20),
  file = fileid,
  orientation = "landscape",
  nosplitin = list(cols = c(trtvar))
)
```
```{r result1, echo=FALSE, message=FALSE, warning=FALSE, test = list(result_v1 = "result")}
tt_to_flextable_j(head(result, 20), tblid)
```

[Download RTF file](`r paste0(tolower(tblid), '.rtf')`)
::::

