---
title: TSFAE21C
subtitle: Subjects With Treatment-emergent Adverse Events by System Organ Class, Preferred Term, and Severity
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}


envsetup_config_name <- "default"

# Path to the combined config file
envsetup_file_path <- file.path("../..", "envsetup.yml")

Sys.setenv(ENVSETUP_ENVIRON = '')
library(envsetup)
loaded_config <- config::get(config = envsetup_config_name, file = envsetup_file_path)
envsetup::rprofile(loaded_config)


dpscomp <- compound
dpspdr <- paste(protocol,dbrelease,rpteff,sep="__")

aptcomp <- compound
aptpdr <- paste(protocol,dbrelease,rpteff,sep="__")

###### Study specific updates (formerly in envre)

dpscomp <- "standards"
dpspdr <- "jjcs__NULL__jjcs - core"

apt <- FALSE

```

## Output

:::: panel-tabset
## {{< fa regular file-lines sm fw >}} Preview

```{r variant1, results='hide', warning = FALSE, message = FALSE}

# Program Name: tsfae21c.R

# Prep Environment

library(envsetup)
library(tern)
library(dplyr)
library(rtables)
library(junco)

# Define script level parameters:

# - Define output ID and file location

tblid <- "TSFAE21c"
fileid <- tblid
tab_titles <- get_titles_from_file(input_path = '../../_data/', tblid)
string_map <- default_str_map

trtvar <- "TRT01A"
popfl <- "SAFFL"
combined_colspan_trt <- TRUE

if (combined_colspan_trt == TRUE) {
  # Set up levels and label for the required combined columns
  add_combo <- add_combo_facet("Combined",
                               label = "Combined",
                               levels = c("Apalutamide", "Apalutamide Subgroup")
  )
  
  # choose if any facets need to be removed - e.g remove the combined column for placebo
  rm_combo_from_placebo <- cond_rm_facets(
    facets = "Combined",
    ancestor_pos = NA,
    value = " ",
    split = "colspan_trt"
  )
  
  mysplit <- make_split_fun(post = list(add_combo, rm_combo_from_placebo))
}

# Process Data:

adsl <- pharmaverseadamjnj::adsl %>%
  filter(!!rlang::sym(popfl) == "Y") %>%
  select(STUDYID, USUBJID, all_of(trtvar), all_of(popfl))

adae <- pharmaverseadamjnj::adae %>%
  filter(TRTEMFL == "Y") %>%
  select(USUBJID, AEBODSYS, AEDECOD, TRTEMFL, AESEV)

# Take maximum severity
adaemax <- adae %>%
  mutate(AESEVN = case_when(toupper(AESEV) == "MILD" ~ 3,
                            toupper(AESEV) == "MODERATE" ~ 2,
                            toupper(AESEV) == "SEVERE" ~ 1,
                            .default = 99
  )) %>%
  arrange(USUBJID, AEBODSYS, AEDECOD, AESEVN) %>%
  group_by(USUBJID, AEBODSYS, AEDECOD) %>%
  slice(1) %>%
  ungroup()

adsl$colspan_trt <- factor(ifelse(adsl[[trtvar]] == "Placebo", " ", "Active Study Agent"),
                           levels = c("Active Study Agent", " ")
)

colspan_trt_map <- create_colspan_map(adsl,
                                      non_active_grp = "Placebo",
                                      non_active_grp_span_lbl = " ",
                                      active_grp_span_lbl = "Active Study Agent",
                                      colspan_var = "colspan_trt",
                                      trt_var = trtvar
)

# join data together
ae <- inner_join(adaemax, adsl, by = c("USUBJID"))

ae <- ae %>%
  mutate(AESEV2 = as.factor(ifelse(is.na(AESEV), "Missing", AESEV)))

if (length(adae$TRTEMFL) == 0) {
  ae <- right_join(adaemax, adsl, by = c("USUBJID"))
  
  ae <- ae %>%
    mutate(AESEV2 = as.factor(ifelse(is.na(AESEV), "Missing", AESEV)))
}

levels(ae$AESEV2) <- c(levels(ae$AESEV), "Missing")

# Define layout and build table:

extra_args_1 <- list(denom = "n_altdf", 
                     .stats = c("count_unique_fraction"))

lyt <- basic_table(
  top_level_section_div = " ",
  show_colcounts = TRUE,
  colcount_format = "N=xx"
) %>%
  split_cols_by("colspan_trt", split_fun = trim_levels_to_map(map = colspan_trt_map))

if (combined_colspan_trt == TRUE) {
  lyt <- lyt %>%
    split_cols_by(trtvar, split_fun = mysplit)
} else {
  lyt <- lyt %>%
    split_cols_by(trtvar)
}

lyt <- lyt %>%
  analyze("TRTEMFL",
          afun = a_freq_j,
          show_labels = "hidden",
          extra_args = append(extra_args_1,
                              list(label = "Subjects with >=1 AE", val = "Y"))
  ) %>%
  split_rows_by("AEBODSYS",
                split_label = "System Organ Class",
                split_fun = trim_levels_in_group("AEDECOD"),
                label_pos = "topleft",
                section_div = c(" "),
                nested = FALSE
  ) %>%
  summarize_row_groups("AEBODSYS",
                       cfun = a_freq_j,
                       extra_args = extra_args_1
  ) %>%
  split_rows_by("AEDECOD",
                split_label = "Preferred Term, n (%)",
                section_div = c(" "),
                nested = TRUE
  ) %>%
  summarize_row_groups("AEDECOD",
                       cfun = a_freq_j,
                       extra_args = extra_args_1
  ) %>%
  analyze("AESEV2",
          afun = a_freq_j,
          extra_args = extra_args_1
  ) %>%
  append_topleft("  Preferred Term, n (%)")

result <- build_table(lyt, ae, alt_counts_df = adsl)

# Post-Processing step to sort by descending count on chosen active treatment columns.

if (length(adae$TRTEMFL) != 0) {
  result <- sort_at_path(result, c("root", "AEBODSYS"), scorefun = jj_complex_scorefun())
  result <- sort_at_path(result, c("root", "AEBODSYS", "*", "AEDECOD"),
                         scorefun = jj_complex_scorefun()
  )
  
  #########################################################################################
  # Post-Processing step to remove all rows where counts are 0
  #########################################################################################
  
  result <- safe_prune_table(result, prune_func = prune_empty_level)
}

# Add titles and footnotes:

result <- set_titles(result, tab_titles)

# Convert to tbl file and output table

tt_to_tlgrtf(string_map = string_map, tt = head(result, 20), file = fileid, orientation = "portrait", label_width_ins = 1.5)
```
```{r result1, echo=FALSE, message=FALSE, warning=FALSE, test = list(result_v1 = "result")}
tt_to_flextable_j(head(result, 20), tblid)
```

[Download RTF file](`r paste0(tolower(tblid), '.rtf')`)
::::

