---
title: TSFAE24C
subtitle: Subjects With Treatment-emergent Adverse Events and Related Treatment-emergent Adverse Events by System Organ Class and Preferred Term
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
envsetup_config_name <- "default"

# Path to the combined config file
envsetup_file_path <- file.path("../..", "envsetup.yml")

Sys.setenv(ENVSETUP_ENVIRON = '')
library(envsetup)
loaded_config <- config::get(config = envsetup_config_name, file = envsetup_file_path)
envsetup::rprofile(loaded_config)


dpscomp <- compound
dpspdr <- paste(protocol,dbrelease,rpteff,sep="__")

aptcomp <- compound
aptpdr <- paste(protocol,dbrelease,rpteff,sep="__")

###### Study specific updates (formerly in envre)

dpscomp <- "standards"
dpspdr <- "jjcs__NULL__jjcs - core"

apt <- FALSE

```

## Output

:::: panel-tabset
## {{< fa regular file-lines sm fw >}} Preview

```{r variant1, results='hide', warning = FALSE, message = FALSE}

# Program Name:              tsfae24c.R

# Prep environment:

library(envsetup)
library(tern)
library(dplyr)
library(rtables)
library(junco)

# Define script level parameters:

tblid <- "TSFAE24c"
fileid <- tblid
popfl <- "SAFFL"
trtvar <- "TRT01A"
tab_titles <- get_titles_from_file(input_path = '../../_data/', tblid)
string_map <- default_str_map

# Process data:

adsl <- pharmaverseadamjnj::adsl %>%
  filter(!!rlang::sym(popfl) == "Y") %>%
  create_colspan_var(
    non_active_grp = "Placebo",
    non_active_grp_span_lbl = " ",
    active_grp_span_lbl = "Active Study Agent",
    colspan_var = "colspan_trt",
    trt_var = trtvar
  ) %>%
  mutate(COLSPAN_REL = "AEs") %>%
  select(
    USUBJID,
    !!rlang::sym(popfl),
    !!rlang::sym(trtvar),
    colspan_trt,
    COLSPAN_REL
  )

adae <- pharmaverseadamjnj::adae %>%
  filter(TRTEMFL == "Y") %>%
  select(USUBJID, TRTEMFL, AEBODSYS, AEDECOD, AEREL)

adae <- inner_join(adae, adsl, by = c("USUBJID"))

# Define layout and build table:

colspan_trt_map <- create_colspan_map(
  adsl,
  non_active_grp = "Placebo",
  non_active_grp_span_lbl = " ",
  active_grp_span_lbl = "Active Study Agent",
  colspan_var = "colspan_trt",
  trt_var = trtvar
)

combodf <- tribble(
  ~valname  , ~label        , ~levelcombo , ~exargs ,
  "RELATED" , "Related AEs" , c("AEs")    , list()
)

extra_args1 <- list(
  .stats = c("count_unique_fraction"),
  subcol_split = "RELATED",
  subcol_var = "AEREL",
  subcol_val = "RELATED"
)

lyt <- basic_table(
  show_colcounts = TRUE,
  colcount_format = "N=xx",
  top_level_section_div = " "
) %>%
  split_cols_by(
    "COLSPAN_REL",
    split_fun = add_combo_levels(combodf, trim = TRUE)
  ) %>%
  split_cols_by(
    "colspan_trt",
    split_fun = trim_levels_to_map(map = colspan_trt_map)
  ) %>%
  split_cols_by(trtvar) %>%
  analyze(
    "TRTEMFL",
    afun = a_freq_subcol_j,
    extra_args = append(
      extra_args1,
      list(
        label = "Subjects with >= 1 AE",
        val = "Y"
      )
    )
  ) %>%
  split_rows_by(
    "AEBODSYS",
    split_label = "System Organ Class",
    label_pos = "topleft",
    split_fun = trim_levels_in_group("AEDECOD"),
    section_div = " ",
    nested = FALSE
  ) %>%
  summarize_row_groups(
    "AEBODSYS",
    cfun = a_freq_subcol_j,
    extra_args = extra_args1
  ) %>%
  analyze("AEDECOD", afun = a_freq_subcol_j, extra_args = extra_args1) %>%
  append_topleft(" Preferred Term, n (%)")

result <- build_table(lyt, adae, alt_counts_df = adsl)

# Post-Processing:

result <- result %>%
  sort_at_path(
    path = c("AEBODSYS"),
    scorefun = cont_n_onecol("AEs.Active Study Agent.Xanomeline High Dose")
  ) %>%
  sort_at_path(
    path = c("AEBODSYS", "*", "AEDECOD"),
    scorefun = score_occurrences_cols(
      "AEs.Active Study Agent.Xanomeline High Dose"
    )
  )

# Add titles and footnotes:

result <- set_titles(result, tab_titles)

# Convert to tbl file and output table:

tt_to_tlgrtf(string_map = string_map, tt = head(result, 25), file = fileid, orientation = "landscape")
```
```{r result1, echo=FALSE, message=FALSE, warning=FALSE, test = list(result_v1 = "result")}
tt_to_flextable_j(head(result, 25), tblid)
```

[Download RTF file](`r paste0(tolower(tblid), '.rtf')`)
::::

