---
title: TSFDTH01
subtitle: Deaths
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
options(docx.add_datetime = FALSE, tidytlg.add_datetime = FALSE)
envsetup_config_name <- "default"

# Path to the combined config file
envsetup_file_path <- file.path("../..", "envsetup.yml")

Sys.setenv(ENVSETUP_ENVIRON = '')
library(envsetup)
loaded_config <- config::get(config = envsetup_config_name, file = envsetup_file_path)
envsetup::rprofile(loaded_config)


dpscomp <- compound
dpspdr <- paste(protocol,dbrelease,rpteff,sep="__")

aptcomp <- compound
aptpdr <- paste(protocol,dbrelease,rpteff,sep="__")

###### Study specific updates (formerly in envre)

dpscomp <- "standards"
dpspdr <- "jjcs__NULL__jjcs - core"

apt <- FALSE

```

## Output

:::: panel-tabset
## {{< fa regular file-lines sm fw >}} Preview

```{r variant1, results='hide', warning = FALSE, message = FALSE}

# Program Name:              tsfdth01.R

# Prep Environment

library(envsetup)
library(tern)
library(dplyr)
library(rtables)
library(junco)

# Define script level parameters:

# - Define output ID and file location

tblid <- "TSFDTH01"
fileid <- tblid
tab_titles <- get_titles_from_file(input_path = '../../_data/', tblid)
string_map <- default_str_map

trtvar <- "TRT01A"
popfl <- "SAFFL"

days <- 30
dthcausevar <- "DTHCAUS"

combined_colspan_trt <- TRUE
risk_diff <- TRUE
rr_method <- "wald"
ctrl_grp <- "Placebo"

if (combined_colspan_trt == TRUE) {
  # Set up levels and label for the required combined columns
  add_combo <- add_combo_facet(
    "Combined",
    label = "Combined",
    levels = c("Xanomeline High Dose", "Xanomeline Low Dose")
  )

  # choose if any facets need to be removed - e.g remove the combined column for placebo
  rm_combo_from_placebo <- cond_rm_facets(
    facets = "Combined",
    ancestor_pos = NA,
    value = " ",
    split = "colspan_trt"
  )

  mysplit <- make_split_fun(post = list(add_combo, rm_combo_from_placebo))
}

# Process Data:

adsl <- pharmaverseadamjnj::adsl %>%
  filter(!!rlang::sym(popfl) == "Y") %>%
  # remove DTHB60FL variable from below if Deaths within 60 days section is not required
  select(
    STUDYID,
    USUBJID,
    all_of(trtvar),
    all_of(popfl),
    DTHFL,
    DTHTRTFL,
    DTHB60FL,
    DTHAFTFL,
    all_of(dthcausevar)
  )

adsl$colspan_trt <- factor(
  ifelse(adsl[[trtvar]] == "Placebo", " ", "Active Study Agent"),
  levels = c("Active Study Agent", " ")
)

if (risk_diff == TRUE) {
  adsl$rrisk_header <- "Risk Difference (%) (95% CI)"
  adsl$rrisk_label <- paste(adsl[[trtvar]], paste("vs", ctrl_grp))
}

adsl <- adsl %>%
  mutate(
    DTHVAR = !!as.name(dthcausevar),
    DTHVAR = as.factor(DTHVAR)
  )

# re-order so OTHER becomes the last category in the table (if there is an OTHER)
is_other <- adsl %>%
  filter(DTHVAR == "OTHER")

if (length(is_other$DTHVAR) != 0) {
  adsl <- adsl %>%
    mutate(DTHVAR = forcats::fct_relevel(DTHVAR, "OTHER", after = Inf))
}

# Convert Reasons to sentence case
adsl$DTHVAR <- stringr::str_to_sentence(adsl$DTHVAR)
adsl$DTHVAR <- as.factor(adsl$DTHVAR)

colspan_trt_map <- create_colspan_map(
  adsl,
  non_active_grp = ctrl_grp,
  non_active_grp_span_lbl = " ",
  active_grp_span_lbl = "Active Study Agent",
  colspan_var = "colspan_trt",
  trt_var = trtvar
)
ref_path <- c("colspan_trt", " ", trtvar, ctrl_grp)

# Define layout and build table:

extra_args_rr <- list(
  method = rr_method,
  .stats = c("count_unique_fraction"),
  ref_path = ref_path,
  riskdiff = TRUE,
  denom = "n_altdf"
)

# check if we actually have any deaths so this can be used for the layout
anydth <- adsl %>%
  filter(DTHFL == "Y")

lyt <- basic_table(
  top_level_section_div = " ",
  show_colcounts = TRUE,
  colcount_format = "N=xx"
) %>%
  split_cols_by(
    "colspan_trt",
    split_fun = trim_levels_to_map(map = colspan_trt_map)
  )

if (combined_colspan_trt == TRUE) {
  lyt <- lyt %>%
    split_cols_by(trtvar, split_fun = mysplit)
} else {
  lyt <- lyt %>%
    split_cols_by(trtvar)
}

if (risk_diff == TRUE) {
  lyt <- lyt %>%
    split_cols_by("rrisk_header", nested = FALSE) %>%
    split_cols_by(
      trtvar,
      labels_var = "rrisk_label",
      split_fun = remove_split_levels("Placebo")
    )
}

if (length(anydth$DTHFL) != 0) {
  lyt <- lyt %>%
    split_rows_by(
      "DTHFL",
      split_fun = keep_split_levels("Y"),
      split_label = "Deaths",
      label_pos = "topleft",
      section_div = " "
    ) %>%
    summarize_row_groups(
      "DTHFL",
      cfun = a_freq_j,
      extra_args = append(extra_args_rr, list(label = "Total deaths"))
    ) %>%
    analyze(
      "DTHVAR",
      var_labels = " ",
      a_freq_j,
      extra_args = extra_args_rr,
      indent_mod = 0,
      show_labels = "hidden"
    ) %>%
    split_rows_by(
      "DTHTRTFL",
      split_fun = keep_split_levels("Y"),
      section_div = " "
    ) %>%
    summarize_row_groups(
      "DTHTRTFL",
      cfun = a_freq_j,
      extra_args = append(
        extra_args_rr,
        list(label = paste0("Deaths within ", days, " days of last dose"))
      )
    ) %>%
    analyze(
      "DTHVAR",
      var_labels = " ",
      afun = a_freq_j,
      extra_args = extra_args_rr,
      indent_mod = 0,
      show_labels = "hidden"
    ) %>%
    split_rows_by(
      "DTHAFTFL",
      split_fun = keep_split_levels("Y"),
      section_div = " "
    ) %>%
    summarize_row_groups(
      "DTHAFTFL",
      cfun = a_freq_j,
      extra_args = append(
        extra_args_rr,
        list(label = paste0("Deaths beyond ", days, " days of last dose"))
      )
    ) %>%
    analyze(
      "DTHVAR",
      var_labels = " ",
      afun = a_freq_j,
      extra_args = extra_args_rr,
      indent_mod = 0,
      show_labels = "hidden"
    ) %>%
    # Remove below section if the Deaths within 60 days section is not required
    split_rows_by(
      "DTHB60FL",
      split_fun = keep_split_levels("Y"),
      section_div = " "
    ) %>%
    summarize_row_groups(
      "DTHB60FL",
      cfun = a_freq_j,
      extra_args = append(
        extra_args_rr,
        list(label = "Deaths within 60 days of first dose")
      )
    ) %>%
    analyze(
      "DTHVAR",
      var_labels = " ",
      afun = a_freq_j,
      extra_args = extra_args_rr,
      indent_mod = 0,
      show_labels = "hidden"
    )
} else {
  lyt <- lyt %>%
    analyze(
      "DTHFL",
      a_freq_j,
      show_labels = "hidden",
      extra_args = append(extra_args_rr, list(label = "Total deaths"))
    )
}

lyt <- lyt %>%
  append_topleft("  Cause of Death, n (%)")

result <- build_table(lyt, adsl, alt_counts_df = adsl)

## Remove the N=xx column headers for the risk difference columns
result <- remove_col_count(result)

# If there is no deaths remove top row and display "No data to display" text
if (length(anydth$DTHFL) == 0) {
  result <- safe_prune_table(
    result,
    prune_func = remove_rows(removerowtext = "Total deaths")
  )
}

# Post-Processing step to sort by descending count on chosen active treatment columns.

if (length(anydth$DTHFL) != 0) {
  result <- sort_at_path(
    result,
    c("root", "DTHFL", "*", "DTHVAR"),
    scorefun = jj_complex_scorefun()
  )
  result <- sort_at_path(
    result,
    c("root", "DTHTRTFL", "*", "DTHVAR"),
    scorefun = jj_complex_scorefun()
  )
  result <- sort_at_path(
    result,
    c("root", "DTHAFTFL", "*", "DTHVAR"),
    scorefun = jj_complex_scorefun()
  )
  result <- sort_at_path(
    result,
    c("root", "DTHB60FL", "*", "DTHVAR"),
    scorefun = jj_complex_scorefun()
  )
}

# Add titles and footnotes:

result <- set_titles(result, tab_titles)

# Convert to tbl file and output table

tt_to_tlgrtf(string_map = string_map, tt = result, file = fileid, orientation = "landscape")
```
```{r result1, echo=FALSE, message=FALSE, warning=FALSE, test = list(result_v1 = "result")}
tt_to_flextable_j(result, tblid)
```

[Download RTF file](`r paste0(tolower(tblid), '.rtf')`)
::::

