---
title: LSIEX02
subtitle: Listing of Study Treatment Batch Lot Number
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(rtables.officer)

envsetup_config_name <- "default"

# Path to the combined config file
envsetup_file_path <- file.path("../..", "envsetup.yml")

Sys.setenv(ENVSETUP_ENVIRON = '')
library(envsetup)
loaded_config <- config::get(config = envsetup_config_name, file = envsetup_file_path)
envsetup::rprofile(loaded_config)


dpscomp <- compound
dpspdr <- paste(protocol,dbrelease,rpteff,sep="__")

aptcomp <- compound
aptpdr <- paste(protocol,dbrelease,rpteff,sep="__")

###### Study specific updates (formerly in envre)

dpscomp <- "standards"
dpspdr <- "jjcs__NULL__jjcs - core"

apt <- FALSE

```

## Output

:::: panel-tabset
## {{< fa regular file-lines sm fw >}} Preview

```{r variant1, results='hide', warning = FALSE, message = FALSE}

# Program Name:              lsiex02.R

# Prep environment

library(envsetup)
library(tern)
library(dplyr)
library(tidyr)
library(rtables)
library(junco)

# Define script level parameters

tblid <- "LSIEX02"
fileid <- tblid
popfl <- "SAFFL"
trtvar <- "TRT01A"
key_cols <- c("COL0", "COL1")
disp_cols <- paste0("COL", 0:6)
tab_titles <- get_titles_from_file(input_path = '../../_data/', tblid)
string_map <- default_str_map

# Process data

adex <- pharmaverseadamjnj::adex %>%
  filter(!!rlang::sym(popfl) == "Y" & ADOSE > 0)

lsting <- adex %>%
  mutate(
    DAEXPDT = as.Date(DAEXPDTC, format = "%Y-%m-%d"),
    DAEXPYR = ifelse(stringr::str_length(sub("T.*", "", DAEXPDTC)) >= 4 &
      substr(sub("T.*", "", DAEXPDTC), 1, 4) != "----",
    substr(sub("T.*", "", DAEXPDTC), 1, 4),
    NA
    ),
    DAEXPMO = toupper(month.abb[
      as.numeric(ifelse(stringr::str_length(sub("T.*", "", DAEXPDTC)) >= 7 &
        substr(sub("T.*", "", DAEXPDTC), 6, 7) != "--",
      substr(sub("T.*", "", DAEXPDTC), 6, 7),
      NA
      ))
    ]),
    DAEXPDAY = ifelse(stringr::str_length(sub("T.*", "", DAEXPDTC)) >= 10 &
      substr(sub("T.*", "", DAEXPDTC), 9, 10) != "--",
    substr(sub("T.*", "", DAEXPDTC), 9, 10),
    NA
    ),
  ) %>%
  unite("DAEXPDTL", DAEXPDAY, DAEXPMO, DAEXPYR,
    sep = "",
    na.rm = TRUE,
    remove = FALSE
  ) %>%
  mutate(
    COL0 = explicit_na(.data[[trtvar]], ""),
    COL1 = explicit_na(USUBJID, ""),
    # Optional Column: COL2/AVISIT
    COL2 = explicit_na(AVISIT, ""),
    # Optional Column: COL3/ASTDT
    COL3 = ifelse(!is.na(ASTDT), paste0(toupper(format(ASTDT, "%d%b%Y"))), ""),
    # Optional Column: COL4/ASTDTM
    COL4 = ifelse(!is.na(ASTDTM), substr(ASTDTM, 12, 16), ""),
    COL5 = explicit_na(EXLOT, ""),
    COL6 = explicit_na(DAEXPDTL, "")
  ) %>%
  arrange(
    COL0, COL1, !is.na(ASTDT), ASTDT, !is.na(ASTDTM), ASTDTM, AVISITN,
    COL2
  )

lsting <- var_relabel(lsting,
  COL0 = "Treatment Group",
  COL1 = "Subject ID",
  # Optional Column: COL2/AVISIT
  COL2 = "Visit",
  # Optional Column: COL3/ASTDT
  # Select appropriate column header label
  # COL3 = "Date Dispensed",
  COL3 = "Date Administered",
  # Optional Column: COL4/ASTDTM
  # Select appropriate column header label
  # COL4 = "Time Dispensed",
  COL4 = "Time Administered",
  COL5 = "Batch Lot Number",
  COL6 = "Batch Lot Expiration Date"
)

# Build listing

result <- rlistings::as_listing(
  df = lsting,
  key_cols = key_cols,
  disp_cols = disp_cols
)

# Add titles and footnotes

result <- set_titles(result, tab_titles)

# Output listing

tt_to_tlgrtf(string_map = string_map, tt = head(result, 30), file = fileid, orientation = "landscape")
```
```{r result1, echo=FALSE, message=FALSE, warning=FALSE, test = list(result_v1 = "result")}
tt_to_flextable_j(head(result,30), theme = theme_docx_default(font_size = 6))
```

[Download RTF file](`r paste0(tolower(tblid), '.rtf')`)
::::

