---
title: TPK01B
subtitle: Matrix Active Study Agent/Analyte Concentrations (units) Over Time
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
envsetup_config_name <- "default"

# Path to the combined config file
envsetup_file_path <- file.path("../..", "envsetup.yml")

Sys.setenv(ENVSETUP_ENVIRON = '')
library(envsetup)
loaded_config <- config::get(config = envsetup_config_name, file = envsetup_file_path)
envsetup::rprofile(loaded_config)


dpscomp <- compound
dpspdr <- paste(protocol,dbrelease,rpteff,sep="__")

aptcomp <- compound
aptpdr <- paste(protocol,dbrelease,rpteff,sep="__")

###### Study specific updates (formerly in envre)

dpscomp <- "standards"
dpspdr <- "jjcs__NULL__jjcs - core"

apt <- FALSE

```

## Output

:::: panel-tabset
## {{< fa regular file-lines sm fw >}} Preview

```{r variant1, results='hide', warning = FALSE, message = FALSE}

# Program Name:              tpk01b

# Prep environment:

library(envsetup)
library(dplyr)
library(rtables)
library(tern)
library(junco)

# Define script level parameters:

tblid <- "TPK01b"
fileid <- tblid

popfl <- "PKFL"
trtvar <- "TRT01A"

trt_grps <- c("Xanomeline High Dose", "Xanomeline Low Dose")

for (i in seq_along(trt_grps)) {
  trt_grp <- trt_grps[i]
  path <- paste0(fileid, "part", i)
  
  ##############################################################################
  # Process data:
  ##############################################################################
  
  adsl <- pharmaverseadamjnj::adsl |>
    filter(.data[[popfl]] == "Y") |>
    select(USUBJID, all_of(trtvar), PKFL) |>
    filter(.data[[trtvar]] == trt_grp) |>
    mutate(colspan = "Observed")
  
  adpc <- pharmaverseadamjnj::adpc |>
    filter(PARAMCD == "XAN") |>
    select(USUBJID, all_of(trtvar), AVISIT, ATPT, AVAL) |>
    filter(.data[[trtvar]] == trt_grp) |>
    inner_join(adsl) |>
    
    # Concatenate and reorder time points
    mutate(AVISIT_ATPT = factor(paste(AVISIT, ATPT, sep = " - "), levels = c(
      "Day 1 - Pre-dose",
      "Day 1 - 5 Min Post-dose",
      "Day 1 - 30 Min Post-dose",
      "Day 1 - 1h Post-dose",
      "Day 1 - 1.5h Post-dose",
      "Day 1 - 2h Post-dose",
      "Day 1 - 4h Post-dose",
      "Day 1 - 0-6h Post-dose",
      "Day 1 - 6h Post-dose",
      "Day 1 - 8h Post-dose",
      "Day 1 - 6-12h Post-dose",
      "Day 1 - 12h Post-dose",
      "Day 1 - 16h Post-dose",
      "Day 1 - 12-24h Post-dose",
      "Day 2 - 24h Post-dose",
      "Day 2 - Pre-dose",
      "Day 2 - 36h Post-dose",
      "Day 2 - 24-48h Post-dose",
      "Day 3 - 48h Post-dose", 
      "Day 3 - Pre-dose"
    )))
  
  ##############################################################################
  # Define layout and build table:
  ##############################################################################
  
  lyt <- basic_table() |>
    split_cols_by(
      var = trtvar,
      show_colcounts = TRUE,
      colcount_format = "N=xx",
      split_fun = drop_split_levels
    ) |>
    
    split_cols_by("colspan") |>
    
    split_rows_by(
      var = "AVISIT_ATPT",
      split_label = "Time Point",
      label_pos = "topleft",
      child_labels = "hidden"
    ) |>
    
    analyze_vars_in_cols(
      vars = "AVAL",
      .stats = c(
        "n",
        "mean",
        "sd",
        "median",
        "min",
        "max",
        "cv",
        "geom_mean"
      ),
      .labels = c(
        n = "N",
        mean = "Mean",
        sd = "SD",
        median = "Med",
        min = "Min",
        max = "Max",
        cv = "% CV",
        geom_mean = "Geometric Mean"
      ),
      .formats = c(
        n = jjcsformat_xx("xx"),
        mean = jjcsformat_xx("xx.xx"),
        sd = jjcsformat_xx("xx.xx"),
        median = jjcsformat_xx("xx.xx"),
        min = jjcsformat_xx("xx.xx"),
        max = jjcsformat_xx("xx.xx"),
        cv = jjcsformat_xx("xx.x"),
        geom_mean = jjcsformat_xx("xx.xx")
      )
    )
  
  result <- build_table(lyt, df = adpc, alt_counts_df = adsl)
  
  ##############################################################################
  # Add titles and footnotes:
  ##############################################################################
  
  result <- set_titles(result, get_titles_from_file(input_path = '../../_data/', tblid)
string_map <- default_str_map)
  
  ##############################################################################
  # Convert to tbl file and output table:
  ##############################################################################
  
  tt_to_tlgrtf(string_map = string_map, tt = head(result, 25), file = path, orientation = "landscape")
}
```
```{r result1, echo=FALSE, message=FALSE, warning=FALSE, test = list(result_v1 = "result")}
tt_to_flextable_j(head(result, 25), tblid)
```

[Download RTF file](`r paste0(tolower(tblid), '.rtf')`)
::::

